backbone: "CLIP-ViT-B/16"
resolution: 224

output_dir: null
print_freq: 10

seed: 0
deterministic: True
gpu: 0
num_workers: 8
prec: "amp"

num_epochs: 10
batch_size: 128
micro_batch_size: 128
lr: 0.01
weight_decay: 5e-4
momentum: 0.9
loss_type: "CE"
classifier: "CosineClassifier"

bias_tuning: False
ln_tuning: False
vpt_shallow: False
vpt_deep: False
adapter: False
adaptformer: True
lora: False
ssf_attn: False
ssf_mlp: False
ssf_ln: False

init_head: "text_feat"
test_ensemble: True
expand: 24

patch: True
head_num: None

cmo: False
use_randaug: False
weighted_alpha: 1