backbone: "IN21K-ViT-B/16"
resolution: 224

output_dir: null
print_freq: 1

seed: 0
deterministic: True
gpu: 0
num_workers: 8
prec: "amp"

num_epochs: 50
batch_size: 128
micro_batch_size: 128
# batch_size: 16
# micro_batch_size: 16
lr: 0.01
# lr: 0.0001
weight_decay: 5e-4
weight_decay_head : 5e-4
momentum: 0.9
loss_type: "LA"
# loss_type: "CE"
classifier: "CosineClassifier"
scale: 25

full_tuning: False  # full fine-tuning

bias_tuning: False
ln_tuning: False
vpt_shallow: False
vpt_deep: False
adapter: False
adaptformer: True
lora: False
ssf_attn: False
ssf_mlp: False
ssf_ln: False

adapter_dim: 128

init_head: None
# init_head: "class_mean"

test_ensemble: True
expand: 24

cmo: False
use_randaug: False
weighted_alpha: 1

normal_label: 10

